Added a new dependency on metadata-extractor version 2.7.2. The reason for this is that the version that Tika pulls down (2.6.2) results in a java.lang.NoSuchMethodError exception being thrown.